/*
 * Microservicio de Usuarios - Undersounds
 *
 * Especificacion OpenAPI del microservicio de \"Usuarios\" dentro del proyecto \"Undersounds\" de GPS/ASEE.  Este microservicio gestiona: - Usuarios y tipos de usuario - Listas de reproduccion personales - Favoritos (canciones, albumes, artistas) - Albumes deseados (wishlist) - Posts en comunidades - Historial de compras  El codigo del proyecto esta disponible en el [repositorio de GitHub](https://github.com/UniExtremadura/proyecto-gps-25-26-ga05).
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"github.com/gin-gonic/gin"
)

type AlbumesDeseadosAPI struct {
}

// Get /usuarios/:idUsuario/deseos/albums
// Obtener lista de albumes deseados (wishlist) 
func (api *AlbumesDeseadosAPI) UsuariosIdUsuarioDeseosAlbumsGet(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Delete /usuarios/:idUsuario/deseos/albums/:idAlbum
// Eliminar un album de la lista de deseos 
func (api *AlbumesDeseadosAPI) UsuariosIdUsuarioDeseosAlbumsIdAlbumDelete(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Post /usuarios/:idUsuario/deseos/albums/:idAlbum
// Añadir un album a la lista de deseos 
func (api *AlbumesDeseadosAPI) UsuariosIdUsuarioDeseosAlbumsIdAlbumPost(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

