/*
 * Microservicio de Usuarios - Undersounds
 *
 * Especificacion OpenAPI del microservicio de \"Usuarios\" dentro del proyecto \"Undersounds\" de GPS/ASEE.  Este microservicio gestiona: - Usuarios y tipos de usuario - Listas de reproduccion personales - Favoritos (canciones, albumes, artistas) - Albumes deseados (wishlist) - Posts en comunidades - Historial de compras  El codigo del proyecto esta disponible en el [repositorio de GitHub](https://github.com/UniExtremadura/proyecto-gps-25-26-ga05).
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"github.com/gin-gonic/gin"
)

type UsuariosAPI struct {
}

// Get /usuarios
// Buscar usuarios por nombre 
func (api *UsuariosAPI) UsuariosGet(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Delete /usuarios/:idUsuario
// Eliminar un usuario por su ID 
func (api *UsuariosAPI) UsuariosIdUsuarioDelete(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Get /usuarios/:idUsuario
// Obtener los datos de un usuario por su ID 
func (api *UsuariosAPI) UsuariosIdUsuarioGet(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Patch /usuarios/:idUsuario
// Modificar los datos de un usuario existente 
func (api *UsuariosAPI) UsuariosIdUsuarioPatch(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Post /usuarios
// Registrar un nuevo usuario 
func (api *UsuariosAPI) UsuariosPost(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

