/*
 * Microservicio de Usuarios - Undersounds
 *
 * Especificacion OpenAPI del microservicio de \"Usuarios\" dentro del proyecto \"Undersounds\" de GPS/ASEE.  Este microservicio gestiona: - Usuarios y tipos de usuario - Listas de reproduccion personales - Favoritos (canciones, albumes, artistas) - Albumes deseados (wishlist) - Posts en comunidades - Historial de compras  El codigo del proyecto esta disponible en el [repositorio de GitHub](https://github.com/UniExtremadura/proyecto-gps-25-26-ga05).
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"github.com/gin-gonic/gin"
)

type PostsDeComunidadAPI struct {
}

// Get /comunidades/:idComunidad/posts
// Obtener posts de una comunidad 
func (api *PostsDeComunidadAPI) ComunidadesIdComunidadPostsGet(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Post /comunidades/:idComunidad/posts
// Crear un nuevo post en una comunidad 
func (api *PostsDeComunidadAPI) ComunidadesIdComunidadPostsPost(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Delete /posts/:idPost
// Eliminar un post 
func (api *PostsDeComunidadAPI) PostsIdPostDelete(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Get /posts/:idPost
// Obtener detalles de un post 
func (api *PostsDeComunidadAPI) PostsIdPostGet(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Patch /posts/:idPost
// Modificar un post 
func (api *PostsDeComunidadAPI) PostsIdPostPatch(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Get /posts/:idPost/respuestas
// Obtener respuestas a un post 
func (api *PostsDeComunidadAPI) PostsIdPostRespuestasGet(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

