/*
 * Microservicio de Usuarios - Undersounds
 *
 * Especificacion OpenAPI del microservicio de \"Usuarios\" dentro del proyecto \"Undersounds\" de GPS/ASEE.  Este microservicio gestiona: - Usuarios y tipos de usuario - Listas de reproduccion personales - Favoritos (canciones, albumes, artistas) - Albumes deseados (wishlist) - Posts en comunidades - Historial de compras  El codigo del proyecto esta disponible en el [repositorio de GitHub](https://github.com/UniExtremadura/proyecto-gps-25-26-ga05).
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"database/sql"
	"encoding/json"
	"fmt"
	"net/http"
	"strconv"

	"github.com/gin-gonic/gin"
)

type FavoritosAPI struct {
	DB *sql.DB
}

const (
	msgInvalidIdUsuario     = "idUsuario inválido"
	msgInvalidParams        = "Parámetros inválidos"

	msgErrGetAlbums         = "Error al obtener álbumes favoritos"
	msgErrAddAlbum          = "Error al añadir álbum a favoritos"
	msgErrDeleteAlbum       = "Error al eliminar álbum favorito"
	msgAlbumNotInFavorites  = "El álbum no estaba en favoritos"

	msgErrGetArtistas       = "Error al obtener artistas favoritos"
	msgErrAddArtista        = "Error al añadir artista a favoritos"
	msgErrDeleteArtista     = "Error al eliminar artista favorito"
	msgArtistaNotInFavorites= "El artista no estaba en favoritos"

	msgErrGetCanciones      = "Error al obtener canciones favoritas"
	msgErrAddCancion        = "Error al añadir canción a favoritos"
	msgErrDeleteCancion     = "Error al eliminar canción favorita"
	msgCancionNotInFavorites= "La canción no estaba en favoritos"
)

// Get /usuarios/:idUsuario/favoritos/albums
// Obtener todos los albumes favoritos de un usuario
func (api *FavoritosAPI) UsuariosIdUsuarioFavoritosAlbumsGet(c *gin.Context) {
	idUsuarioStr := c.Param("idUsuario")
	idUsuario, err := strconv.Atoi(idUsuarioStr)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": msgInvalidIdUsuario})
		return
	}

	rows, err := api.DB.Query(`SELECT idAlbum FROM fav_album WHERE idUsuario = $1`, idUsuario)
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": msgErrGetAlbums})
		return
	}
	defer rows.Close()

	var favoritos []GetAlbumFavorito

	for rows.Next() {
		var idAlbum int32
		if err := rows.Scan(&idAlbum); err != nil {
			fmt.Printf("Error scan idAlbum: %v\n", err)
			continue
		}

		album, err := api.fetchAlbum(idAlbum)
		if err != nil {
			fmt.Printf("fetchAlbum error: %v\n", err)
			continue
		}
		favoritos = append(favoritos, *album)
	}

	c.JSON(http.StatusOK, gin.H{
		"status":    "OK",
		"favoritos": favoritos,
	})
}

// Delete /usuarios/:idUsuario/favoritos/albums/:idAlbum
// Eliminar un album de favoritos
func (api *FavoritosAPI) UsuariosIdUsuarioFavoritosAlbumsIdAlbumDelete(c *gin.Context) {
	idUsuarioStr := c.Param("idUsuario")
	idAlbumStr := c.Param("idAlbum")

	idUsuario, err1 := strconv.Atoi(idUsuarioStr)
	idAlbum, err2 := strconv.Atoi(idAlbumStr)

	if err1 != nil || err2 != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": msgInvalidParams})
		return
	}

	result, err := api.DB.Exec(`
		DELETE FROM fav_album
		WHERE idUsuario = $1 AND idAlbum = $2
	`, idUsuario, idAlbum)

	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": msgErrDeleteAlbum})
		return
	}

	rowsAffected, err := result.RowsAffected()
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": msgErrDeleteAlbum})
		return
	}
	if rowsAffected == 0 {
		c.JSON(http.StatusNotFound, gin.H{"error": msgAlbumNotInFavorites})
		return
	}

	c.JSON(200, gin.H{"status": "OK"})
}

// Post /usuarios/:idUsuario/favoritos/albums/:idAlbum
// Añadir un album a favoritos
func (api *FavoritosAPI) UsuariosIdUsuarioFavoritosAlbumsIdAlbumPost(c *gin.Context) {
	idUsuarioStr := c.Param("idUsuario")
	idAlbumStr := c.Param("idAlbum")

	idUsuario, err1 := strconv.Atoi(idUsuarioStr)
	idAlbum, err2 := strconv.Atoi(idAlbumStr)

	if err1 != nil || err2 != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": msgInvalidParams})
		return
	}

	_, err := api.DB.Exec(`
		INSERT INTO fav_album (idUsuario, idAlbum)
		VALUES ($1, $2)
		ON CONFLICT DO NOTHING
	`, idUsuario, idAlbum)

	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": msgErrAddAlbum})
		return
	}

	c.JSON(200, gin.H{"status": "OK"})
}

// Get /usuarios/:idUsuario/favoritos/artistas
// Obtener todos los artistas favoritos de un usuario
func (api *FavoritosAPI) UsuariosIdUsuarioFavoritosArtistasGet(c *gin.Context) {
	idUsuarioStr := c.Param("idUsuario")
	idUsuario, err := strconv.Atoi(idUsuarioStr)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": msgInvalidIdUsuario})
		return
	}

	rows, err := api.DB.Query(`
        SELECT u.id, u.nombre
        FROM fav_artista f
        JOIN usuario u ON f.idArtista = u.id
        WHERE f.idUsuario = $1
    `, idUsuario)
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": msgErrGetArtistas})
		return
	}
	defer rows.Close()

	var favoritos []GetArtistaFavorito

		for rows.Next() {
		var a GetArtistaFavorito
		if err := rows.Scan(&a.IdArtista, &a.Nombre); err != nil {
			fmt.Printf("Error scan artista: %v\n", err)
			continue
		}
		favoritos = append(favoritos, a)
	}

	c.JSON(http.StatusOK, gin.H{
		"status":    "OK",
		"favoritos": favoritos,
	})
}

// Delete /usuarios/:idUsuario/favoritos/artistas/:idArtista
// Eliminar un artista de favoritos
func (api *FavoritosAPI) UsuariosIdUsuarioFavoritosArtistasIdArtistaDelete(c *gin.Context) {
	idUsuarioStr := c.Param("idUsuario")
	idArtistaStr := c.Param("idArtista")

	idUsuario, err1 := strconv.Atoi(idUsuarioStr)
	idArtista, err2 := strconv.Atoi(idArtistaStr)

	if err1 != nil || err2 != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": msgInvalidParams})
		return
	}

	result, err := api.DB.Exec(`
		DELETE FROM fav_artista
		WHERE idUsuario = $1 AND idArtista = $2
	`, idUsuario, idArtista)

	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": msgErrDeleteArtista})
		return
	}

	rowsAffected, err := result.RowsAffected()
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": msgErrDeleteArtista})
		return
	}
	if rowsAffected == 0 {
		c.JSON(http.StatusNotFound, gin.H{"error": msgArtistaNotInFavorites})
		return
	}

	c.JSON(200, gin.H{"status": "OK"})
}

// Post /usuarios/:idUsuario/favoritos/artistas/:idArtista
// Añadir un artista a favoritos
func (api *FavoritosAPI) UsuariosIdUsuarioFavoritosArtistasIdArtistaPost(c *gin.Context) {
	idUsuarioStr := c.Param("idUsuario")
	idArtistaStr := c.Param("idArtista")

	idUsuario, err1 := strconv.Atoi(idUsuarioStr)
	idArtista, err2 := strconv.Atoi(idArtistaStr)

	if err1 != nil || err2 != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": msgInvalidParams})
		return
	}

	_, err := api.DB.Exec(`
		INSERT INTO fav_artista (idUsuario, idArtista)
		VALUES ($1, $2)
		ON CONFLICT DO NOTHING
	`, idUsuario, idArtista)

	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": msgErrAddArtista})
		return
	}

	c.JSON(200, gin.H{"status": "OK"})
}

// Get /usuarios/:idUsuario/favoritos/canciones
// Obtener todas las canciones favoritas de un usuario
func (api *FavoritosAPI) UsuariosIdUsuarioFavoritosCancionesGet(c *gin.Context) {
	idUsuarioStr := c.Param("idUsuario")
	idUsuario, err := strconv.Atoi(idUsuarioStr)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": msgInvalidIdUsuario})
		return
	}

	rows, err := api.DB.Query(`SELECT idCancion FROM fav_cancion WHERE idUsuario = $1`, idUsuario)
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": msgErrGetCanciones})
		return
	}
	defer rows.Close()

	var favoritos []GetCancionFavorita

		for rows.Next() {
		var idCancion int32
		if err := rows.Scan(&idCancion); err != nil {
			fmt.Printf("Error scan idCancion: %v\n", err)
			continue
		}

		cancion, err := api.fetchCancion(idCancion)
		if err != nil {
			continue
		}
		favoritos = append(favoritos, *cancion)
	}

	c.JSON(http.StatusOK, gin.H{
		"status":    "OK",
		"favoritos": favoritos,
	})
}

// Delete /usuarios/:idUsuario/favoritos/canciones/:idCancion
// Eliminar una canción de favoritos
func (api *FavoritosAPI) UsuariosIdUsuarioFavoritosCancionesIdCancionDelete(c *gin.Context) {
	idUsuarioStr := c.Param("idUsuario")
	idCancionStr := c.Param("idCancion")

	idUsuario, err1 := strconv.Atoi(idUsuarioStr)
	idCancion, err2 := strconv.Atoi(idCancionStr)

	if err1 != nil || err2 != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": msgInvalidParams})
		return
	}

	result, err := api.DB.Exec(`
		DELETE FROM fav_cancion
		WHERE idUsuario = $1 AND idCancion = $2
	`, idUsuario, idCancion)

	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": msgErrDeleteCancion})
		return
	}

	rowsAffected, err := result.RowsAffected()
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": msgErrDeleteCancion})
		return
	}
	if rowsAffected == 0 {
		c.JSON(http.StatusNotFound, gin.H{"error": msgCancionNotInFavorites})
		return
	}

	c.JSON(200, gin.H{"status": "OK"})
}

// Post /usuarios/:idUsuario/favoritos/canciones/:idCancion
// Añadir una canción a favoritos
func (api *FavoritosAPI) UsuariosIdUsuarioFavoritosCancionesIdCancionPost(c *gin.Context) {
	idUsuarioStr := c.Param("idUsuario")
	idCancionStr := c.Param("idCancion")

	idUsuario, err1 := strconv.Atoi(idUsuarioStr)
	idCancion, err2 := strconv.Atoi(idCancionStr)

	if err1 != nil || err2 != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": msgInvalidParams})
		return
	}

	_, err := api.DB.Exec(`
		INSERT INTO fav_cancion (idUsuario, idCancion)
		VALUES ($1, $2)
		ON CONFLICT DO NOTHING
	`, idUsuario, idCancion)

	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": msgErrAddCancion})
		return
	}

	c.JSON(200, gin.H{"status": "OK"})
}

func (api *FavoritosAPI) fetchCancion(idCancion int32) (*GetCancionFavorita, error) {
	resp, err := http.Get(fmt.Sprintf("http://contenido-app:8080/canciones/%d", idCancion))
	if err != nil || resp.StatusCode != 200 {
		return nil, fmt.Errorf("error consultando canción")
	}
	defer resp.Body.Close()

	var data struct {
		Id     int32  `json:"id"`
		Nombre string `json:"nombre"`
	}

	if err := json.NewDecoder(resp.Body).Decode(&data); err != nil {
		return nil, err
	}

	return &GetCancionFavorita{
		IdCancion: data.Id,
		Nombre:    data.Nombre,
	}, nil
}

func (api *FavoritosAPI) fetchAlbum(idAlbum int32) (*GetAlbumFavorito, error) {
	url := fmt.Sprintf("http://contenido-app:8080/albums/%d", idAlbum)
	resp, err := http.Get(url)
	if err != nil {
		return nil, fmt.Errorf("error HTTP: %v", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		return nil, fmt.Errorf("HTTP status %d", resp.StatusCode)
	}

	var album GetAlbumFavorito
	if err := json.NewDecoder(resp.Body).Decode(&album); err != nil {
		return nil, fmt.Errorf("error decodificando JSON: %v", err)
	}

	// log para debug
	fmt.Printf("fetchAlbum id=%d => %+v\n", idAlbum, album)

	// validar que realmente se obtuvo un nombre
	if album.Nombre == "" {
		return nil, fmt.Errorf("album con id %d no tiene nombre o no existe", idAlbum)
	}

	return &album, nil
}
