/*
 * Microservicio de Usuarios - Undersounds
 *
 * Especificacion OpenAPI del microservicio de \"Usuarios\" dentro del proyecto \"Undersounds\" de GPS/ASEE.  Este microservicio gestiona: - Usuarios y tipos de usuario - Listas de reproduccion personales - Favoritos (canciones, albumes, artistas) - Albumes deseados (wishlist) - Posts en comunidades - Historial de compras  El codigo del proyecto esta disponible en el [repositorio de GitHub](https://github.com/UniExtremadura/proyecto-gps-25-26-ga05).
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"github.com/gin-gonic/gin"
)

type ListasDeReproduccionAPI struct {
}

// Delete /listas/:idLista/canciones/:idCancion
// Eliminar una cancion de una lista de reproduccion 
func (api *ListasDeReproduccionAPI) ListasIdListaCancionesIdCancionDelete(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Post /listas/:idLista/canciones/:idCancion
// Añadir una cancion a una lista de reproduccion 
func (api *ListasDeReproduccionAPI) ListasIdListaCancionesIdCancionPost(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Delete /listas/:idLista
// Eliminar una lista de reproduccion 
func (api *ListasDeReproduccionAPI) ListasIdListaDelete(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Get /listas/:idLista
// Obtener detalles de una lista de reproduccion 
func (api *ListasDeReproduccionAPI) ListasIdListaGet(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Patch /listas/:idLista
// Modificar una lista de reproducción 
func (api *ListasDeReproduccionAPI) ListasIdListaPatch(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Get /usuarios/:idUsuario/listas
// Obtener todas las listas de reproduccion de un usuario 
func (api *ListasDeReproduccionAPI) UsuariosIdUsuarioListasGet(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Post /usuarios/:idUsuario/listas
// Crear una nueva lista de reproduccion 
func (api *ListasDeReproduccionAPI) UsuariosIdUsuarioListasPost(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

