/*
 * Microservicio de Usuarios - Undersounds
 *
 * Especificacion OpenAPI del microservicio de \"Usuarios\" dentro del proyecto \"Undersounds\" de GPS/ASEE.  Este microservicio gestiona: - Usuarios y tipos de usuario - Listas de reproduccion personales - Favoritos (canciones, albumes, artistas) - Albumes deseados (wishlist) - Posts en comunidades - Historial de compras  El codigo del proyecto esta disponible en el [repositorio de GitHub](https://github.com/UniExtremadura/proyecto-gps-25-26-ga05).
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"github.com/gin-gonic/gin"
)

type ComprasAPI struct {
}

// Get /usuarios/:idUsuario/compras
// Obtener historial de compras de un usuario 
func (api *ComprasAPI) UsuariosIdUsuarioComprasGet(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Post /usuarios/:idUsuario/compras/:idMerch
// Registrar una compra de merchandising 
func (api *ComprasAPI) UsuariosIdUsuarioComprasIdMerchPost(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

