/*
 * Microservicio de Usuarios - Undersounds
 *
 * Especificacion OpenAPI del microservicio de \"Usuarios\" dentro del proyecto \"Undersounds\" de GPS/ASEE.  Este microservicio gestiona: - Usuarios y tipos de usuario - Listas de reproduccion personales - Favoritos (canciones, albumes, artistas) - Albumes deseados (wishlist) - Posts en comunidades - Historial de compras  El codigo del proyecto esta disponible en el [repositorio de GitHub](https://github.com/UniExtremadura/proyecto-gps-25-26-ga05).
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"time"
)

type Post struct {

	Id int32 `json:"id"`

	Comentario string `json:"comentario"`

	// ID del post padre si es una respuesta
	PostPadre *int32 `json:"postPadre,omitempty"`

	IdUsuario int32 `json:"idUsuario"`

	IdComunidad int32 `json:"idComunidad"`

	FechaCreacion time.Time `json:"fechaCreacion,omitempty"`
}
