/*
 * Microservicio de Usuarios - Undersounds
 *
 * Especificacion OpenAPI del microservicio de \"Usuarios\" dentro del proyecto \"Undersounds\" de GPS/ASEE.  Este microservicio gestiona: - Usuarios y tipos de usuario - Listas de reproduccion personales - Favoritos (canciones, albumes, artistas) - Albumes deseados (wishlist) - Posts en comunidades - Historial de compras  El codigo del proyecto esta disponible en el [repositorio de GitHub](https://github.com/UniExtremadura/proyecto-gps-25-26-ga05).
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type UsuarioCreate struct {

	Nombre string `json:"nombre"`

	Correo string `json:"correo"`

	Contrasena string `json:"contrasena"`

	Direccion string `json:"direccion,omitempty"`

	Telefono string `json:"telefono,omitempty"`

	Descripcion string `json:"descripcion,omitempty"`

	UrlImagen string `json:"urlImagen,omitempty"`

	// ID del tipo de usuario
	Tipo int32 `json:"tipo"`
}
